import { IPFS_GATEWAY } from '../index'
import { Team } from './types'

const teams: Team[] = [
  {
    id: 1,
    name: 'Afterburn',
    description: "description",
    images: {
      lg: 'Afterburn.png',
      md: 'Afterburn.png',
      sm: 'Afterburn.png',
      alt: 'Afterburn.png',
      ipfs: `${IPFS_GATEWAY}/QmXKzSojwzYjtDCVgR6mVx7w7DbyYpS7zip4ovJB9fQdMG/syrup-storm.png`,
    },
    background: 'syrup-storm-bg.svg',
    textColor: '#191326',
    users: 0,
    points: 0,
  },
  {
    id: 2,
    name: 'Bullchargers',
    description: "description",
    images: {
      lg: "Bullchargers.png",
      md: "Bullchargers.png",
      sm: "Bullchargers.png",
      alt: "Bullchargers.png",
      ipfs: `${IPFS_GATEWAY}/QmXKzSojwzYjtDCVgR6mVx7w7DbyYpS7zip4ovJB9fQdMG/fearsome-flippers.png`,
    },
    background: 'fearsome-flippers-bg.svg',
    textColor: '#FFFFFF',
    users: 0,
    points: 0,
  },
  {
    id: 3,
    name: 'Fero',
    description: 'description',
    images: {
      lg: "fero.png",
      md: "fero.png",
      sm: "fero.png",
      alt: "fero.png",
      ipfs: `${IPFS_GATEWAY}/QmXKzSojwzYjtDCVgR6mVx7w7DbyYpS7zip4ovJB9fQdMG/chaotic-cakers.png`,
    },
    background: 'chaotic-cakers-bg.svg',
    textColor: '#191326',
    users: 0,
    points: 0,
  },
  {
    id: 4,
    name: 'GolSquad',
    description: 'description',
    images: {
      lg: "GolSquad.png",
      md: "GolSquad.png",
      sm: "GolSquad.png",
      alt: "GolSquad.png",
      ipfs: `${IPFS_GATEWAY}/QmXKzSojwzYjtDCVgR6mVx7w7DbyYpS7zip4ovJB9fQdMG/chaotic-cakers.png`,
    },
    background: 'chaotic-cakers-bg.svg',
    textColor: '#191326',
    users: 0,
    points: 0,
  },
  {
    id: 5,
    name: 'MagikaFc',
    description: 'description',
    images: {
      lg: "MagikaFc.png",
      md: "MagikaFc.png",
      sm: "MagikaFc.png",
      alt: "MagikaFc.png",
      ipfs: `${IPFS_GATEWAY}/QmXKzSojwzYjtDCVgR6mVx7w7DbyYpS7zip4ovJB9fQdMG/chaotic-cakers.png`,
    },
    background: 'chaotic-cakers-bg.svg',
    textColor: '#191326',
    users: 0,
    points: 0,
  },  
  {
    id: 6,
    name: 'Nemesis',
    description: 'description',
    images: {
      lg: "Nemesis.png",
      md: "Nemesis.png",
      sm: "Nemesis.png",
      alt: "Nemesis.png",
      ipfs: `${IPFS_GATEWAY}/QmXKzSojwzYjtDCVgR6mVx7w7DbyYpS7zip4ovJB9fQdMG/chaotic-cakers.png`,
    },
    background: 'chaotic-cakers-bg.svg',
    textColor: '#191326',
    users: 0,
    points: 0,
  },
  {
    id: 7,
    name: 'The Pack',
    description: 'description',
    images: {
      lg: "ThePack.png",
      md: "ThePack.png",
      sm: "ThePack.png",
      alt: "ThePack.png",
      ipfs: `${IPFS_GATEWAY}/QmXKzSojwzYjtDCVgR6mVx7w7DbyYpS7zip4ovJB9fQdMG/chaotic-cakers.png`,
    },
    background: 'chaotic-cakers-bg.svg',
    textColor: '#191326',
    users: 0,
    points: 0,
  },
  {
    id: 8,
    name: 'Thunderbolts',
    description: 'description',
    images: {
      lg: "Thunderbolts.png",
      md: "Thunderbolts.png",
      sm: "Thunderbolts.png",
      alt: "Thunderbolts.png",
      ipfs: `${IPFS_GATEWAY}/QmXKzSojwzYjtDCVgR6mVx7w7DbyYpS7zip4ovJB9fQdMG/chaotic-cakers.png`,
    },
    background: 'chaotic-cakers-bg.svg',
    textColor: '#191326',
    users: 0,
    points: 0,
  },
  {
    id: 9,
    name: 'Ultimus',
    description: 'description',
    images: {
      lg: "Ultimus.png",
      md: "Ultimus.png",
      sm: "Ultimus.png",
      alt: "Ultimus.png",
      ipfs: `${IPFS_GATEWAY}/QmXKzSojwzYjtDCVgR6mVx7w7DbyYpS7zip4ovJB9fQdMG/chaotic-cakers.png`,
    },
    background: 'chaotic-cakers-bg.svg',
    textColor: '#191326',
    users: 0,
    points: 0,
  },
  {
    id: 10,
    name: 'Winterbers',
    description: 'description',
    images: {
      lg: "Winterbers.png",
      md: "Winterbers.png",
      sm: "Winterbers.png",
      alt: "Winterbers.png",
      ipfs: `${IPFS_GATEWAY}/QmXKzSojwzYjtDCVgR6mVx7w7DbyYpS7zip4ovJB9fQdMG/chaotic-cakers.png`,
    },
    background: 'chaotic-cakers-bg.svg',
    textColor: '#191326',
    users: 0,
    points: 0,
  },

]

export default teams
